<?php


namespace App\Decorators;


class OrderCommentsGetter extends OrderDecorator
{
    public function GetOrder()
    {
        $order = parent::GetOrder(); // TODO: Change the autogenerated stub
        $comments = $order->comments()->get();
        $order->comments = $comments;
        return $order;
    }

    private function GetCommentsTo($order)
    {

    }
}
