<?php


namespace App\Decorators;


use App\Builders\OrderBuilder;
use App\Models\OrderStatus;

class OrderStatusColored extends OrderDecorator
{


    protected function modifyOrder()
    {
        $order = $this->orderBuilder->GetOrder();
        $order->color = $order->status()->first()->color;
        return $order;
    }
//    public function GetOrder()
//    {
////        $order =  parent::GetOrder(); // TODO: Change the autogenerated stub
//        $order->color = $order->status()->first()->color;
//        return $order;
//    }
}
