<?php


namespace App\Decorators;


use App\Builders\OrderBuilder;
use App\Models\OrderStatus;

class OrderStatusSetter extends OrderDecorator
{
    protected $status;
    public function __construct(OrderBuilder $builder, OrderStatus $status)
    {
        $this->status = $status;
        parent::__construct($builder);
    }

    public function GetOrder()
    {
        $order =  parent::GetOrder(); // TODO: Change the autogenerated stub
        $order->status = $this->status;
        return $order;
    }
}
