<?php


namespace App\Decorators;


use App\Builders\OrderBuilder;
use App\Models\OrderStatus;

class OrderStatusColored extends OrderDecorator
{
    public function __construct(OrderBuilder $builder)
    {
        parent::__construct($builder);
    }

    public function GetOrder()
    {
        $order =  parent::GetOrder(); // TODO: Change the autogenerated stub
        $order->color = $order->status()->first()->color;
        return $order;
    }
}
