<?php


namespace App\Decorators;


class OrderCommentsGetter extends OrderDecorator
{

    protected function modifyOrder()
    {
        $order = $this->orderBuilder->GetOrder();
        $comments = $order->comments()->latest()->get();
        $order->comments = $comments;
        return $order;
    }
//    public function GetOrder()
//    {
//        $order = parent::GetOrder(); // TODO: Change the autogenerated stub
//        $comments = $order->comments()->latest()->get();
//        $order->comments = $comments;
//        return $order;
//    }
//
//    private function GetCommentsTo($order)
//    {
//
//    }
}
